In [6]:
import pandas as pd

In [2]:
ls

2017_02_24_Case_Study_BI_Intern_Analysis_of_loan_offers.xlsx
2017_02_24_Case_Study_BI_Intern_Marketing_Conversion.xlsx
2019_02_BI_Interns_Challenge.pdf
Untitled.ipynb

In [19]:
data = pd.read_excel('2017_02_24_Case_Study_BI_Intern_Analysis_of_loan_offers.xlsx')

In [20]:
data

,CASE STUDY - Angebote/Banken,Unnamed: 1,Unnamed: 2
0,NaN,NaN,NaN
1,Please prepare a short presentation in PowerPo...,NaN,NaN
2,1,How many customers get No loan offer?,NaN
3,2,How is the distribution of loan offers by Lead...,NaN
4,3,Calculate the average loan offers for the cust...,NaN
5,4,Does the result (see 3) looks different betwee...,NaN
6,NaN,NaN,NaN
7,Erläuterungen zu den Tabellenblättern als Hilf...,NaN,NaN
8,NaN,NaN,NaN
9,"Tabelle ""offer sum per account""",NaN,NaN
10,Spalte,Erklärung,Description
11,a_id1,Account_id des Kunden,Account_id of the customer
12,anmeldetag,NaN,Signup date of the customer
13,age,Alter des Kunden,Age of the customer
14,berufsgruppe,NaN,Employment group of the customer
15,einkommen,NaN,Income of the customer
16,lead_canal,Marketingkanal Herkunft des Kunden\n- Affiliat...,Lead channel of the customer\n- affiliates\n- ...
17,no_brokerage,Angebotsvielfalt\n- true : nur smavaprivat Ang...,Number of offered Products:\n- true: only Smav...
18,beratung_erhalten,Telefonische Beratung erhalten?,Customer got an advisory
19,beratung_erfolgreich,Erfolgreich?,Advisory successfull
20,current_rating,Scoring des Kunden,Scoring/Rating of the customer
21,failed_appl,#Anzahl fehlgeschlagene Kreditanfrage,Count of failed applications
22,denied_appl,#Anzahl abgelehnte Kreditanfrage,Count of denied applications
23,applied_appl,#Anzahl erfolgreiche Kreditanfrage = Kreditang...,Count of successfull applications = Customer g...
24,min_effzins,niedrigster Effektivzins,Minimum effective Rate
25,max_effzins,höchster Effektivzins,Maximum effective Rate
26,avg_amount,durchschnittlich angebotener Kreditbetrag,Average offered Amount